### PR TITLE
Fix 761 - Store and use the original ValueExpression

### LINKED ISSUE #761: CommandButtonSingleClick: Problem in Datatable
If you have a Datatable with a CommandButton in the first column.

```xml
<p:column>
    <p:commandButton id="btnActions" value="Button" 
         oncomplete="alert('#{component.clientId}');" immediate="true" process="@this" />
<p:column>
```

Because in encodeMarkup we are calling button.resolvewidgetVar() it is resolving it incorrectly.

All of the buttons in my table are being rendered with widgetVar :0:

```
frmMain:tblTest:0:btnActions
frmMain:tblTest:0:btnActions
frmMain:tblTest:0:btnActions
frmMain:tblTest:0:btnActions
```

instead of 

```
frmMain:tblTest:0:btnActions
frmMain:tblTest:1:btnActions
frmMain:tblTest:2:btnActions
frmMain:tblTest:3:btnActions
```

### PR DESCRIPTION
**Pull request by jepsar**
Fix https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/761 including EL

### CODE REVIEW

**Comment by jepsar** [comment]
Wait.. I missed something else.. let me have another look at this tomorrow. I think the only thing that's currently missing is the `buildDomEvent` part.

File: src/main/java/org/primefaces/extensions/renderer/CommandButtonSingleClickRenderer.java [hunk 1]
```diff
@@ -57,13 +54,17 @@ protected String getToggleJS(final String widgetVar, final boolean enabled) {
...
-        if (value != null) {
-            return value;
+    protected String getAttributeValue(final FacesContext context, final CommandButton button, final String attribute) {
+        String key = "CommandButtonSingleClickRenderer:" + attribute;
+        ValueExpression ve = (ValueExpression) button.getAttributes().get(key);
+        if (ve == null) {
+            ve = button.getValueExpression(attribute);
+        }
+        if (ve != null) {
+            button.getAttributes().put(key, ve);
```
Comment (jepsar) [inline src/main/java/org/primefaces/extensions/renderer/CommandButtonSingleClickRenderer.java]: Don't think we need to store the expression. `button.getValueExpression(attribute)` should do.

File: src/main/java/org/primefaces/extensions/renderer/CommandButtonSingleClickRenderer.java [hunk 2]
```diff
@@ -57,13 +54,17 @@ protected String getToggleJS(final String widgetVar, final boolean enabled) {
...
+            return (String) ve.getValue(context.getELContext());
```
Comment (jepsar) [inline src/main/java/org/primefaces/extensions/renderer/CommandButtonSingleClickRenderer.java]: I think we must throw in `buildDomEvent` as used in the `commandButton` renderer.

File: src/main/java/org/primefaces/extensions/renderer/CommandButtonSingleClickRenderer.java (hunk 1 above)
Comment (melloware) [reply src/main/java/org/primefaces/extensions/renderer/CommandButtonSingleClickRenderer.java]: Did you test this out?  I was thinking the same thing that we need to store off the expression before it gets evaluated.

File: src/main/java/org/primefaces/extensions/renderer/CommandButtonSingleClickRenderer.java (hunk 2 above)
Comment (melloware) [reply src/main/java/org/primefaces/extensions/renderer/CommandButtonSingleClickRenderer.java]: Agreed.

File: src/main/java/org/primefaces/extensions/renderer/CommandButtonSingleClickRenderer.java (hunk 1 above)
Comment (jepsar) [reply src/main/java/org/primefaces/extensions/renderer/CommandButtonSingleClickRenderer.java]: No, didn't test this yet. I was going to.

Comment (jepsar) [reply src/main/java/org/primefaces/extensions/renderer/CommandButtonSingleClickRenderer.java]: Yeah, we don't need to store them.

File: src/main/java/org/primefaces/extensions/renderer/CommandButtonSingleClickRenderer.java (hunk 2 above)
Comment (jepsar) [reply src/main/java/org/primefaces/extensions/renderer/CommandButtonSingleClickRenderer.java]: Sorry for the fuzz, it was too late to code yesterday 😄. `buildDomEvent` will be handled when we call `super.encodeMarkup(context, button);`.

File: src/main/java/org/primefaces/extensions/renderer/CommandButtonSingleClickRenderer.java [hunk 3]
```diff
@@ -29,23 +29,24 @@
...
             button.setOncomplete(prefix(onComplete, getToggleJS(widgetVar, true)));
         }
         super.encodeMarkup(context, button);
     }
 
     protected boolean isEligible(final CommandButton button) {
-        return button.isAjax() && button.isRendered() && !button.isDisabled() && !isConfirmation(button);
+        return button.isAjax()
+               && button.isRendered()
+               && button.getActionExpression() != null
```
Comment (jepsar) [inline src/main/java/org/primefaces/extensions/renderer/CommandButtonSingleClickRenderer.java:47]: @melloware this will prevent the issue you found earlier today.

**Comment by melloware** [comment]
I am going to merge and test some more.
