### PR TITLE
Fix #137: InputPlace component

### LINKED ISSUE #137: New Component: InputPlace
Add google place autocomplete component.

https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete

Since we already have Geocoding and Rev. Geocoding from Google, we should also have other google maps features like Place autocomplete etc.

### LINKED ISSUE #1482: InputPhone: Not respecting inputStyleClass
### Describe the bug

using `inputStyleClass="test"` you will not see test appear on the input.

### Reproducer

_No response_

### Expected behavior

class should be applied

### PrimeFaces Extensions version

13.0.7

### JSF implementation

All

### JSF version

2.3

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by melloware**
Fix #137: InputPlace component
Fix #1482 

image

cc @NicolaIsotta

### CODE REVIEW

**Comment by melloware** [comment]
I am going to add another example linking the InputPlace to GMap.

**Comment by melloware** [comment]
Need to add long and short values for country and possible other fields like name.

File: core/src/main/java/org/primefaces/extensions/component/inputplace/InputPlaceRenderer.java [hunk 1]
```diff
@@ -0,0 +1,113 @@
...
+
+        decodeBehaviors(context, inputPlace);
+
+        String clientId = inputPlace.getClientId(context);
+        String submittedValue = context.getExternalContext().getRequestParameterMap().get(clientId);
+
+        if (submittedValue != null) {
+            int maxlength = inputPlace.getMaxlength();
+            if (maxlength > 0 && submittedValue.length() > maxlength) {
+                submittedValue = LangUtils.substring(submittedValue, 0, maxlength);
```
Comment (jepsar) [inline core/src/main/java/org/primefaces/extensions/component/inputplace/InputPlaceRenderer.java:59]: This is kind of weird. Maybe we should log a warning here so the user can consider using a larger maximum length in their model.

File: core/src/main/java/org/primefaces/extensions/model/inputplace/Place.java [hunk 2]
```diff
@@ -0,0 +1,174 @@
...
+        this.country = params.get(clientId + "_country");
+        this.latitude = Double.parseDouble(params.get(clientId + "_lat"));
+        this.longitude = Double.parseDouble(params.get(clientId + "_lng"));
+        this.administrativeAreaLevel1 = params.get(clientId + "_administrative_area_level_1");
+        this.administrativeAreaLevel2 = params.get(clientId + "_administrative_area_level_2");
+        this.administrativeAreaLevel3 = params.get(clientId + "_administrative_area_level_3");
+        this.types = params.get(clientId + "_types");
+    }
+
+    public Place(String placeId, String formattedAddress, String addressLine, String postalCode, String city, String state, String country,
```
Comment (jepsar) [inline core/src/main/java/org/primefaces/extensions/model/inputplace/Place.java]: Wow! Sonar does not like when the amount of parameters exceeds 7, and neither do I 🙈. Maybe we could have a builder instead?

**Review by jepsar — CHANGES_REQUESTED** [review]
I found two small things to consider.

File: core/src/main/java/org/primefaces/extensions/model/inputplace/Place.java (hunk 2 above)
Comment (jepsar) [reply core/src/main/java/org/primefaces/extensions/model/inputplace/Place.java]: Is this even used? (Just did a rough scan). Maybe we an simply delete it. Or make the fields non-final.

File: core/src/main/java/org/primefaces/extensions/component/inputplace/InputPlaceRenderer.java (hunk 1 above)
Comment (melloware) [reply core/src/main/java/org/primefaces/extensions/component/inputplace/InputPlaceRenderer.java:59]: This is copied directly from InputTextRenderer.java in PF?

File: core/src/main/java/org/primefaces/extensions/model/inputplace/Place.java (hunk 2 above)
Comment (melloware) [reply core/src/main/java/org/primefaces/extensions/model/inputplace/Place.java]: Agreed I was just following your pattern but I will remove the constructor!

File: core/src/main/java/org/primefaces/extensions/component/inputplace/InputPlaceRenderer.java (hunk 1 above)
Comment (jepsar) [reply core/src/main/java/org/primefaces/extensions/component/inputplace/InputPlaceRenderer.java:59]: Ah, okay, was thinking it might have been that Google's result was too large for the field's maxlength. But I guess that's clipped in the UI / JS.

**Review by jepsar — DISMISSED** [review]

**Comment by melloware** [comment]
@jepsar working on a custom Address Entry form using InputPlace + GMap + InputPhone.  

I automatically set the InputPhone `initialCountry="#{testView.selectedPlace.countryCode}"` to the Google Place returned Country Code!

image

I did find one minor issue with InputPhone when trying to use a Responsive form.  It won't size the field even with `w-full`

```xml
<div class="field col-12 md:col-6">
    <p:outputLabel value="Primary contact phone" for="@next" />
    <pe:inputPhone id="txtPhone" initialCountry="#{testView.selectedPlace.countryCode}" value="#{testView.phone}" required="true"
        styleClass="w-full" inputStyleClass="w-full" formatOnDisplay="true" />
</div>
```

Its because the outer `span` of course ignores size because its a span and the inner Input `w-full` expands to the width of the ITI Div.  So the only way I could get it to behave the way I wanted was to add CSS...

```css
/* InputPhone Full Width */
.iti {
    width: 100%;
}
```
